<?php

namespace Database\Seeders;

use App\Models\Products\Product;
use App\Models\Sales\SaleHeader;
use App\Models\Store\ProductInput;
use App\Models\Store\ProductInputHeader;
use App\Models\User;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\PaymentType;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $data = require 'database/seeders/data/products.php';
        Product::factory()->createMany($data);

    }


    public function v2(): void

    {
        // Product::factory()->createMany(
        //     [
        //         ['id' => 1, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بيبي جوي رقم واحد مواليد 66", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 2, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بيبي جوي رقم 483", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 3, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بيبي جوي رقم 2 66", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 4, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بيبي جوي عائلي عبوه 44 رقم 4", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 5, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "كونفي مواليد رقم 1 44", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 6, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "كونفي رقم 702", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 7, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "كونفي رقم 603", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 8, 'unit_price' => 150, 'barcode' => '', 'name_ar' => "كونفي رقم 4 50", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 9, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "مناديل مبلله دادي عبوه 72", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 10, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "مناديل مبلله زين عبوه 120 حبه", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 11, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "فاين قل عايلي 1300 الاصفر", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 12, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حليب فرانس ليه رقم 1", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 13, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حليب فرانس ليه رقم 2", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 14, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حليب رجلاك رقم 1", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 15, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حليب رجلاك رقم 2", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 16, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حليب رجلاك رقم 3", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 17, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حليب فرانس ليه رقم 3", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 18, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "رز مصری غذام", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 19, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بسكويت بسكي اطفال .", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 20, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "سيرلاك غذاء مبكت منوع.", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 21, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "اعواد اذان خشب 100", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 22, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "اعواد اذن خشب صيني 200 حبه خليل كبير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 23, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "معجون دابر بالأعشاب مع الفرشاة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 24, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "سجنال معجون وسط الاصلي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 25, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "معجون سجنال صغير اصلي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 26, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "معجون سجنال كبير سعودي 125 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 27, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "فرش استان سبتادینت", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 28, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "فرش اسنان سيلكون الأصلي دكتور", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 29, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "فرش اطفال اورنج ابو غطا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 30, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "صابون جونسون اطفال جديد", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 31, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "صابون مينا بابايا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 32, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "صابون ديتول كبير اصلي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 33, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "صابون لوكس صغير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 34, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "صابون لايفبوي سعودي صغير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 35, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "صابون دوف صغير المالي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 36, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "رضاعات الامير كبير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 37, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "رضاعات مواليد الأمير 60 ملي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 38, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "رضاعات بتاتو وسط معتم 150 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 39, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "زيت الزيتون المروى", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 40, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "زيت الزيتون ليدي بلاص 175 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 41, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "- زيت جونسون اطفال الاصلي 200 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 42, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "زيت اطفال بيدا 200 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 43, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "- زيت نونو 200 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 44, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بودره كوبر 400 جرام مع شامبو 100 مل دعايه", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 45, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بودره كوبر صغير شامبو دعايه 50 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 46, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بودره كوبر كبير 600 مع شامبو 100 مل دعايه", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 47, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بودره كوبر وسط 200 مع شامبو 50 مل دعايه", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 48, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "شحم كوبرا 180 جرام وسط", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 49, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حفاضات لاكي بالغين كبير 30 حبة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 50, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "حفاضات لاكي بالغين وسط 30 حبة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 51, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "شحم كوبرا 180 جرام وسط", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 52, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "شحم كوبر صغير جدا 45 جرام", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 53, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "زيت فاتيكا منوع صغير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 54, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "زيت فاتيكا منوع كبير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 55, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "شامبو اطفال بيبي شوف 100 ملي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 56, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "شامبو اطفال بيبي شوف 200 ملي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 57, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "شامبو اطفال بيبي شوف 800 ملى -", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 58, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "نيقياء ألماني كبير 250 جرام", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 59, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "نيفياء ألماني وسط", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 60, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "كريم جليسوليد كبير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 61, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "گریم جليسوليد وسط", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 62, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "كريم جليسوليد صغير مع الاضافة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 63, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "لصقة عمليات 55 عبوة 50 سران", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 64, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "لصق عمليات 2010 عبوه 25", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 65, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "لصق عمليات تايجر 2510", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 66, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "غذاء ريرى بدون مرتجع", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 67, 'unit_price' => 1500, 'barcode' => '9501101272248', 'name_ar' => "اوجمين شراب ۲۲۸ ملجم الدوانية الحديثة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 68, 'unit_price' => 1100, 'barcode' => '9501101270138', 'name_ar' => "موكسالين ٢٥٠ ملجم شراب الدوائية الحديثة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 69, 'unit_price' => 1400, 'barcode' => '9501101270190', 'name_ar' => "او جمين ١٥٦ ملجم شراب الدوائية الحديثة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 70, 'unit_price' => 1800, 'barcode' => '9501101270206', 'name_ar' => "اوجمين ۳۱۲ ملجم شراب الدوائية الحديثة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 71, 'unit_price' => 1900, 'barcode' => '9501101270930', 'name_ar' => "اوجمين ٤٥٧ ملجم شراب الدوائية الحديثة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 72, 'unit_price' => 400, 'barcode' => '9501101270619', 'name_ar' => "فومين ٧٥ اقراص الدوائية الحديثة", 'name_en' => "vomin", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 73, 'unit_price' => 5000, 'barcode' => '6291100082711', 'name_ar' => "كبير ميبو مرهم ٣٠ جرام جلفار", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 74, 'unit_price' => 1000, 'barcode' => '6221094500786', 'name_ar' => "جوافا شراب ۱۲۰ مل الرشيد سعال", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 75, 'unit_price' => 500, 'barcode' => '6221088021440', 'name_ar' => "نيتروماك ريتارد ٢.٥ ملجم ٦٠ك الفتح", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 76, 'unit_price' => 800, 'barcode' => '6223000012062', 'name_ar' => "فاركونسيل ١٢٥ ملجم شراب ٨٠ مل فاركو موكسالين", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 77, 'unit_price' => 900, 'barcode' => '6223000012079', 'name_ar' => "فاركونسيل ٢٥٠ منجم شراب ٨٠ مل قار کو موكسالين", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 78, 'unit_price' => 150, 'barcode' => '6221151015307', 'name_ar' => "فوار سي فيتامين سي ۱۰۰۰ مل ظروف فاركو ", 'name_en' => "pharco", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 79, 'unit_price' => 100, 'barcode' => '6223000011515', 'name_ar' => "يوريكول فرار ١٢ كيس فاركو", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 80, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "اسبرين مغلف ٧٥ ملجم اقراص المحضار اخوان", 'name_en' => "aspirin 75mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 81, 'unit_price' => 1000, 'barcode' => '540323725902', 'name_ar' => "سيبرولون ٢٥ ملح أقراص الكتون أمير الدين", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 82, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => "كلين انما حقن شرجية كبار العزاني", 'name_en' => "kleen ename_enma 135ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 83, 'unit_price' => 1400, 'barcode' => '6291109120100', 'name_ar' => "بندول شراب للرضع بنكة الفراولة المنصوب", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 84, 'unit_price' => 2200, 'barcode' => '6291109120681', 'name_ar' => "بندول شراب أزرق للأطفال اليكسير ١٠٠ مل المنصوب", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 85, 'unit_price' => 300, 'barcode' => '6091403219964', 'name_ar' => "سولبادين فوار المنصوب", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 86, 'unit_price' => 80, 'barcode' => '6291109120339', 'name_ar' => "بندول اكستر - المنصوب وكالة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 87, 'unit_price' => 1250, 'barcode' => '5997001359426', 'name_ar' => "نورمادبين 5 ملجم اقراص بلقيس", 'name_en' => "normodipiname_en 5mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 88, 'unit_price' => 1650, 'barcode' => '5997001359433', 'name_ar' => "نورمادبين ١٠ ملم اقراص بلقيس", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 89, 'unit_price' => 950, 'barcode' => '8901117265158', 'name_ar' => "اتروليب ١٠ ملجم اقراص ٣٠ ٤ سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 90, 'unit_price' => 1350, 'barcode' => '8901117266049', 'name_ar' => "اتروليب ۲۰ ملجم اقراص ٣٠ سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 91, 'unit_price' => 2300, 'barcode' => '8901117266018', 'name_ar' => "اتروليب ٤٠ ملجم اقراص ۱۰ ق سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 92, 'unit_price' => 1100, 'barcode' => '8901117266445', 'name_ar' => "ديتور ١٠ ملجم اقراص سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 93, 'unit_price' => 1500, 'barcode' => '8901117265974', 'name_ar' => "ديتور ۲۰ ملجم اقراص سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 94, 'unit_price' => 1000, 'barcode' => '8901117268616', 'name_ar' => "بانتوسيك ٤٠ ملجم اقراص سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 95, 'unit_price' => 4500, 'barcode' => '8002660033543', 'name_ar' => "دوفلاك شراب الراقة بدون مرتجع", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 96, 'unit_price' => 800, 'barcode' => '4031571068980', 'name_ar' => "نيفدي دينك ريتارد ۲۰ ملجم ۱۰۰ الغزالي", 'name_en' => "nifedi-denk 20 retard", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 97, 'unit_price' => 800, 'barcode' => '9504000288747', 'name_ar' => "ايبوفلام شراب ۱۰۰ مل كبير شفاكو", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 98, 'unit_price' => 300, 'barcode' => '9504000269173', 'name_ar' => "اسبيكوت ٧٥ ملجم اقراص شفاكو أسبرين مختلف", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 99, 'unit_price' => 1700, 'barcode' => '9504000269340', 'name_ar' => "كلوفال ٧٥ ملح اقراص ۲۸ قرص شفاكو بلافيكس كلوبي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 100, 'unit_price' => 1200, 'barcode' => '9504000288334', 'name_ar' => "اكسوبان ٤٠ ملجم كبسول ٣٠ ك بانتوبرازول شفاكو", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 101, 'unit_price' => 50, 'barcode' => '9504000269203', 'name_ar' => "فولتين دي تي شفاكو ايمفيناك", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 102, 'unit_price' => 30, 'barcode' => '9504000269692', 'name_ar' => "امول اقراص صغير شفاكر", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 103, 'unit_price' => 50, 'barcode' => '9504000269814', 'name_ar' => "امول اكسترا شريطين اقراص شفاكو", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 104, 'unit_price' => 100, 'barcode' => '9504000288198', 'name_ar' => "ميوفيت سي أكياس ۱۰۰۰ ملجم شفاكو فيتامين سي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 105, 'unit_price' => 50, 'barcode' => '9504000269265', 'name_ar' => "او ميتوب ۲۰ ملجم اقراص شفاكو", 'name_en' => "ometop", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 106, 'unit_price' => 1000, 'barcode' => '6211057011039', 'name_ar' => "فيت سي فيتامين سي صافي فوار القادري ", 'name_en' => "vit-c 1000mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 107, 'unit_price' => 1000, 'barcode' => '6211057021038', 'name_ar' => "كالسيفيت كالسيوم فيتامين سي فوار القادري ", 'name_en' => "calcivit-c", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 108, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "سولباقيز فوار رويال سولبادين", 'name_en' => "solpafizz 65mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 109, 'unit_price' => 750, 'barcode' => '6224000486693', 'name_ar' => "کولداکت شراب بیوفارم فلوكيت فلودرين", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 110, 'unit_price' => 50, 'barcode' => '6224000486075', 'name_ar' => "كولداكت كبسول بيوفارما فلوتاب", 'name_en' => "coldact", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 111, 'unit_price' => 100, 'barcode' => '6291103730459', 'name_ar' => "امفيناك دي تي ٥٠ ملجم ك النهدي ديكلوفين", 'name_en' => "emifenac 50", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 112, 'unit_price' => 450, 'barcode' => '8901040310024', 'name_ar' => "زبین شراب رنتل الجبر فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 113, 'unit_price' => 300, 'barcode' => '8901040310031', 'name_ar' => "زبين ۲۰۰ ملجم زنتل / اقراص الجبر فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 114, 'unit_price' => 700, 'barcode' => '6221043012971', 'name_ar' => "ماء سيد شراب الوراقي ماء غريب", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 115, 'unit_price' => 1500, 'barcode' => '6221025025234', 'name_ar' => "ابیدون ١٢٥ ملجم شراب أمون القاهرة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 116, 'unit_price' => 700, 'barcode' => 'ٍأ-012-01-253', 'name_ar' => "بيروفين قطر سباء فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 117, 'unit_price' => 750, 'barcode' => '745604596718', 'name_ar' => "هستات شراب ١٠٠ مل سباء فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 118, 'unit_price' => 750, 'barcode' => '745604597227', 'name_ar' => "موتلين ٦٠ ملجم شراب سباء فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 119, 'unit_price' => 700, 'barcode' => 'ٍأ-012-03-072', 'name_ar' => "هكساديل مضمضه ١٠٠ مل سباء فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 120, 'unit_price' => 1850, 'barcode' => '745604598699', 'name_ar' => "فالسيترى ٢٦/٢٤ ملجم ٣٠ قرص ساكو بلاص سفرماد", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 121, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => "بانتوفكيس بانتوبرازول ٤٠ فيال اميال فارما ", 'name_en' => "pantofix", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 122, 'unit_price' => 250, 'barcode' => '745604596725', 'name_ar' => "هستات اقرص ۲۰ ق سباء فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 123, 'unit_price' => 700, 'barcode' => '745604597241', 'name_ar' => "موتلين ٣٠ مل قطر سباء فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 124, 'unit_price' => 400, 'barcode' => '8904092907648', 'name_ar' => "يوتابين قيال ١.٢ فيال لاااااااب بعوم", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 125, 'unit_price' => 1750, 'barcode' => '8941100359600', 'name_ar' => "جارديان ۱۰ ملج القرص ايمبافت ابن القادري", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 126, 'unit_price' => 1650, 'barcode' => '8941100359617', 'name_ar' => "جارديان ٢٥ ملجم اقرص ايمپافنت ابن القادري -", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 127, 'unit_price' => 1400, 'barcode' => '9501101277120', 'name_ar' => "ايمبا ١٠ ملجم اقراص العالميه ايمباقنت", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 128, 'unit_price' => 2100, 'barcode' => '9501101277168', 'name_ar' => "ايمبا ٢٥ ملجم اقراص العالميه ايمبافنت", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 129, 'unit_price' => 800, 'barcode' => 'إُ-01-029-11', 'name_ar' => "أمبروفين فراولة ۱۰۰مل اليمنية المصرية 7", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 130, 'unit_price' => 1900, 'barcode' => '6251106160158', 'name_ar' => "لينوبريل ١٠ ملجم اقراص الدولية الاردنية", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 131, 'unit_price' => 1250, 'barcode' => '6251106160103', 'name_ar' => "لينوبريل 5ملجم اقراص الدولية الأردنية", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 132, 'unit_price' => 400, 'barcode' => '8901117266414', 'name_ar' => "اسبين 100 ملجم اقراص سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 133, 'unit_price' => 50, 'barcode' => '8901117264298', 'name_ar' => "لوماك ۲۰ منجم كبسول أشرطة سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 134, 'unit_price' => 3200, 'barcode' => '', 'name_ar' => "ميبو مرهم صغير أبو زيد", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 135, 'unit_price' => 400, 'barcode' => '6212035090381', 'name_ar' => "فاديرين 81 ملجم اقراص هيلثي فارما جوسبرين -", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 136, 'unit_price' => 1300, 'barcode' => '8905887002258', 'name_ar' => "ابيكسان هيل 5 ملجم اقراص ابيكسا هيلان", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 137, 'unit_price' => 50, 'barcode' => '8904159404622', 'name_ar' => "سكو فاست اقراص العابد امفيناك بدون مرتجع", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 138, 'unit_price' => 800, 'barcode' => '6210236134187', 'name_ar' => "بوفين شراب ۱۰۰مل الخياط امبروفين شراب", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 139, 'unit_price' => 4500, 'barcode' => '3664798036558', 'name_ar' => "بلافيكس ٧٥ ملجم اقراص الصباري -بانتوبرازول ٤٠ فيال اميال فارما بالتوفيكس", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 140, 'unit_price' => 800, 'barcode' => '9501101270145', 'name_ar' => "موكسالين ١٢٥ ملجم شراب الدوائية الحديثة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 141, 'unit_price' => 900, 'barcode' => '6221000001666', 'name_ar' => "توسكان شراب الجبل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 142, 'unit_price' => 750, 'barcode' => '6221000003042', 'name_ar' => "بيستول ۲٫٥ ملغ اقراص الجبل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 143, 'unit_price' => 1000, 'barcode' => '6221000003059', 'name_ar' => "بیستول ٥ ملغ اقراص عادي الجبل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 144, 'unit_price' => 1300, 'barcode' => '6221000003295', 'name_ar' => "سوفيكان ٢٠ ملغ اقراص الجبل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 145, 'unit_price' => 1000, 'barcode' => '6221000003264', 'name_ar' => "سوفيكان ١٠ ملح أقراص الجبل الحكمه", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 146, 'unit_price' => 700, 'barcode' => '', 'name_ar' => "موتيل ١٠٠مل موتلين شراب العالمية", 'name_en' => "motil 6mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 147, 'unit_price' => 2000, 'barcode' => '', 'name_ar' => "نيولاكس ۱۰۰ مل شراب العالمية لاكسولاك", 'name_en' => "neolax 100mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 148, 'unit_price' => 400, 'barcode' => '8901120014767', 'name_ar' => "هايبين ٥٠٠مل اقراص الجبل أموكسيل ۱۰ ش", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 149, 'unit_price' => 1500, 'barcode' => '6223003972745', 'name_ar' => "بیمفاست ۱۰۰۰ ملجم فيال العربية فوربار", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 150, 'unit_price' => 1000, 'barcode' => '6221508163118', 'name_ar' => "زوراكسون ۱۰۰۰ ملجم وريدي الفتح فورسيف", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 151, 'unit_price' => 1000, 'barcode' => '6222012201587', 'name_ar' => "سيفوران 1 جرام فيال فارکو اور تاکسیم", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 152, 'unit_price' => 1400, 'barcode' => '6222012235209', 'name_ar' => "باراسيتامول قرب برفلجان فاركو", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 153, 'unit_price' => 1100, 'barcode' => '8901149000833', 'name_ar' => "اور تکسیم 1 جرام فيال الجبل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 154, 'unit_price' => 1900, 'barcode' => '8901149030717', 'name_ar' => "سيفتاد ۱۰۰۰ قيال فوربار الجبل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 155, 'unit_price' => 2300, 'barcode' => '8901117303881', 'name_ar' => "قوربار اجرام فيال سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 156, 'unit_price' => 3200, 'barcode' => '6221042445602', 'name_ar' => "انسولين اتش بيو ار فيال أصفر) سيديكو الحارث", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 157, 'unit_price' => 1000, 'barcode' => '6221077121915', 'name_ar' => "هيبارين صوديوم ٥٠٠٠ وحدة عبوة 3 أمبولات جديد الحارث", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 158, 'unit_price' => 650, 'barcode' => '8901086090058', 'name_ar' => "سيبروفلوكساسين محلول العافية سيبلوكس", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 159, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "ديكساميتازون امبول فلهوم", 'name_en' => "dexamethasone 8mg/2ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 160, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => "زجاج برفلجان قرب زجاج فلهوم", 'name_en' => "paracetamol interavenous infusion 1000mg/100ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 161, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "ديكستروز ٤٠% امبول رويال فارما بالحبه الواحده", 'name_en' => "dextrose 40% 20ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 162, 'unit_price' => 1200, 'barcode' => '', 'name_ar' => "براسيتامول مغذيات زجاج رويال بر فلجان رویامول", 'name_en' => "royamol paracetamol 1g", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 163, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "اقيل امبول رويال فارما", 'name_en' => "allvil 20mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 164, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "بليمازول امبول رويال فارما ريمو بلازا", 'name_en' => "plazivom 10mg ", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 165, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "بي كومبلكس أمبول رويال فارما", 'name_en' => "vb complex", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 166, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "فيتامين سي أمبول ٥٠٠ رويال فارما", 'name_en' => "remano-c", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 167, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "جنتاميسين أمبول ۸۰ ملجم رويال فارما", 'name_en' => "gentamicin 80mg 2ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 168, 'unit_price' => 1000, 'barcode' => '4602565014841', 'name_ar' => "متريندازول قرب جال فارما فلاجيل بدون موصل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 169, 'unit_price' => 3200, 'barcode' => '', 'name_ar' => "انترابيم فيال مياس 1 جرام سيفبيم قوربار", 'name_en' => "intrapime cefepime", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 170, 'unit_price' => 2200, 'barcode' => '', 'name_ar' => "باراكونيكا اجرام فيال محلات مياس برفلجان زجاجة", 'name_en' => "paraconica 1000mg iv", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 171, 'unit_price' => 700, 'barcode' => '4048846002914', 'name_ar' => "كمبونينت فيال ۲۰ ف أرض الجنتين كومبيفيت", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 172, 'unit_price' => 500, 'barcode' => '8904092903008', 'name_ar' => "دوبروس ۲۰۰ مل امبول دوبامين بعوم", 'name_en' => "dopress 200 200mg/5ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 173, 'unit_price' => 8200, 'barcode' => '', 'name_ar' => " تینام ٥٠٠ ملجم بان مبنيم مهدي الشاعر وکیل مختوم", 'name_en' => "imipenem cilastatine 500mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 174, 'unit_price' => 5500, 'barcode' => '6192405001783', 'name_ar' => "فانكومايسين اجرام فيال الشاعر فانكولون ۱۰۰۰", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 175, 'unit_price' => 1700, 'barcode' => '6192405002018', 'name_ar' => "ستو بالجيك برفلجان بارستامول مغذية الشاعر", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 176, 'unit_price' => 900, 'barcode' => '', 'name_ar' => "سيبروفلوكساسين قرب الجيش سيبلوكس سيبروكيد", 'name_en' => "ciprofloxacin intravenous inf 200mg/100ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 177, 'unit_price' => 750, 'barcode' => '8901117290723', 'name_ar' => "سيبلاسيف اجرام فيال سيبلا", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 178, 'unit_price' => 800, 'barcode' => '8901117290792', 'name_ar' => "سيبلاسيف ٥٠٠ ملجم فيال سيبلا", 'name_en' => "ciplacef 500", 'scientific_name' => '', 'company_id' => 3],
        //         ['id' => 179, 'unit_price' => 6800, 'barcode' => '8699814260018', 'name_ar' => "سیلاكيب ٥٠٠ جرام فيال تينام رسام الشاعر", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 180, 'unit_price' => 6000, 'barcode' => '8699814270536', 'name_ar' => "موبيم ا مجم فيال رسام الشاعر میرونیم مورنیم بدون مرتجع", 'name_en' => "mopem 1g iv", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 181, 'unit_price' => 500, 'barcode' => '', 'name_ar' => "دايميد ۲۰ منجم امبول الربيعي ديتور ١٠ امبول", 'name_en' => "torasemide injection 10mg/ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 182, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "مغذيات سكر الجبل", 'name_en' => "dextrose 5% injection 5D", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 183, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "رنجر مغذيات الجبل", 'name_en' => "lactated ringer\'s 500ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 184, 'unit_price' => 700, 'barcode' => '', 'name_ar' => " فلاجيل قرب مع الموصلات اميال فارما بدون مرتجع", 'name_en' => "metronidazole injection usp 100ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 185, 'unit_price' => 800, 'barcode' => 'ciprofloxacin ', 'name_ar' => " روها ليفوفلوكساسين قرب ۱۰۰ مل روها فارما معى الموصل ليلوباكت", 'name_en' => " rehciprofloxacin injection 100ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 186, 'unit_price' => 1000, 'barcode' => 'levofloxacin', 'name_ar' => " روها سيبروفلوكساسين قرب ۱۰۰ مل روها فارما معى الموصل سيبلوكس", 'name_en' => "levofloxacin rehciprofloxacin infusion", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 187, 'unit_price' => 400, 'barcode' => '4840982002748', 'name_ar' => " اوندر يسترون امبول ۸ ملجم صادق البرحي ايمست", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 188, 'unit_price' => 6500, 'barcode' => '8435373702077', 'name_ar' => " سالاتاز ٤٥ فيال الأمل تاركت", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 189, 'unit_price' => 800, 'barcode' => '6223003990800', 'name_ar' => " لازكس امبول الصباري", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 190, 'unit_price' => 500, 'barcode' => '89023994864363', 'name_ar' => " هيتاسون ۱۰۰ ملجم فيال فارما بيدا هيدروكرتزون", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 191, 'unit_price' => 400, 'barcode' => '89023995654697', 'name_ar' => " بروسيوم ١٠ امبول امبولات فارما بيدا مغناسيوم", 'name_en' => "Brosium 10ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 192, 'unit_price' => 500, 'barcode' => '8908005809432', 'name_ar' => " سيفتر یاکسون أكوي اجم فيال تعافي فارما سي ون سيبلاسيف", 'name_en' => "ceftriaxone ", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 193, 'unit_price' => 5500, 'barcode' => '8906051740600', 'name_ar' => " نازکت کوزمابيتاز ٤,٥ ملجم قرب الجيش تازكت", 'name_en' => "cozmapitaz ", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 194, 'unit_price' => 600, 'barcode' => '8906051740716', 'name_ar' => " كورما تكسي اجرام فيال اور تكسيم سيفوتاكسيم الجيش و", 'name_en' => "cozmataxi 1000mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 195, 'unit_price' => 500, 'barcode' => '8901117078666', 'name_ar' => " ديتور امبول عبوة ۲۰ امبوله ابوزيد سيبلا ٢٠ أم", 'name_en' => "dytor 10mg/ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 196, 'unit_price' => 7300, 'barcode' => '8908005809418', 'name_ar' => " ميراكوي اجم فيال تعافي فارما ميرونيم", 'name_en' => "meraqua 1g", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 197, 'unit_price' => 3700, 'barcode' => '8908005809500', 'name_ar' => " افسيناف اجم فيال فانكومايسين تعافي فارما", 'name_en' => "avcinaf 1g", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 198, 'unit_price' => 4300, 'barcode' => 'enoxaparin taafi 40mg/0.4ml', 'name_ar' => " اینوکس بارين ٤٠٠٠ و دتعافي فارما ٢ أمبول", 'name_en' => "enoxaparin taafi 40mg/0.4ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 199, 'unit_price' => 5500, 'barcode' => 'enoxaparin taafi 60mg/0.6ml', 'name_ar' => " اینو كسبارين ٦٠٠٠ و دتعافي فارما ٢ امبول", 'name_en' => "enoxaparin taafi 60mg/0.6ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 200, 'unit_price' => 3800, 'barcode' => '8906004260278', 'name_ar' => " کابرین ۲۵۰۰۰ و.د فيال فارما بيوتك هيبارين", 'name_en' => "caprinn 25000", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 201, 'unit_price' => 600, 'barcode' => '8904240117240', 'name_ar' => " ملح مغنيات القطريفي", 'name_en' => "sodium chloride 0.9%", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 202, 'unit_price' => 600, 'barcode' => '', 'name_ar' => " مخلوط مغذيات القطريفي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 203, 'unit_price' => 3000, 'barcode' => '', 'name_ar' => " فانكوبال ۱۰۰۰ ملجم فيال أميال فانكوميسين", 'name_en' => "vancobal 1000mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 204, 'unit_price' => 1800, 'barcode' => '', 'name_ar' => " موكسيبال مغذيات اميال فارما موكساسيب", 'name_en' => "moxibal 400mg/100ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 205, 'unit_price' => 250, 'barcode' => '8908021304201', 'name_ar' => " فير سدرين ٢ ملي أمبول لازكس بريميم ديرين", 'name_en' => "fursederren 2ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 206, 'unit_price' => 300, 'barcode' => '8908021304171', 'name_ar' => " درسترون ۲ ملي أمبول ايمست بریمیم دیرین", 'name_en' => "derrosetron 2mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 207, 'unit_price' => 4300, 'barcode' => '', 'name_ar' => " ليفيتام ٥٠٠ ملجم فيال كيبرا بیوسنسورس بيواكتف", 'name_en' => "levetam 500mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 208, 'unit_price' => 6700, 'barcode' => '6291100085248', 'name_ar' => " فاتكولون ۱۰۰۰ ملجم فيال جلفار", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 209, 'unit_price' => 700, 'barcode' => '', 'name_ar' => " روها میترندازول ۱۰۰ ما قرب روها فارما معى الموصل فلاجيل", 'name_en' => "rehmetronidazole 100ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 210, 'unit_price' => 850, 'barcode' => '', 'name_ar' => "قساطر سلكون مقاس 16", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 211, 'unit_price' => 850, 'barcode' => '', 'name_ar' => "قساطر سلكون مقاس 14 ", 'name_en' => "قسطرة 14", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 212, 'unit_price' => 850, 'barcode' => '', 'name_ar' => "قساطر سلكون مقاس 12", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 213, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => "قساطر سلكون ابو 10", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 214, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => "قساطر سلكون مقاس 6", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 215, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => "قساطر سلكون مقاس 8", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 216, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "قرب بول", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 217, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "شاش معقم 10*10 عبوة 50", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 218, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "جلفز معقم ماليزي 7.5", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 219, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "رایز تیوب مقاس 16", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 220, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "رايز تيوب مقاس 14", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 221, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "رایز تیوب مقاس 12", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 222, 'unit_price' => 8500, 'barcode' => '', 'name_ar' => "سنترلاين مقاس 7", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 223, 'unit_price' => 9300, 'barcode' => '', 'name_ar' => "سنتر لاين مقاس 3", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 224, 'unit_price' => 350, 'barcode' => '', 'name_ar' => "قطن ابو 50 جرام", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 225, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "رايز تيوب مقاس 8", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 226, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "فيدنق تيوب 10", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 227, 'unit_price' => 500, 'barcode' => '', 'name_ar' => "قطن ابو 100 جرام", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 228, 'unit_price' => 1800, 'barcode' => '', 'name_ar' => "قطن 500 جرام", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 229, 'unit_price' => 3300, 'barcode' => '', 'name_ar' => "قطن ابو 1000 جرام", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 230, 'unit_price' => 1100, 'barcode' => '', 'name_ar' => "قطن ابو 250", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 231, 'unit_price' => 400, 'barcode' => '', 'name_ar' => "كمام اكسجين اسمول", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 232, 'unit_price' => 500, 'barcode' => '', 'name_ar' => "كمام اكسجين مديم", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 233, 'unit_price' => 500, 'barcode' => '', 'name_ar' => "كمام اكسجين كبار", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 234, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "كمام نيو بليزر اسمول", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 235, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "كمام نيو بليزر لارج", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 236, 'unit_price' => 250, 'barcode' => '', 'name_ar' => "اندرباد صيني عبوة 25", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 237, 'unit_price' => 4300, 'barcode' => '', 'name_ar' => "سركت تخدير اطفال", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 238, 'unit_price' => 2300, 'barcode' => '', 'name_ar' => "سركت تخدير كبار", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 239, 'unit_price' => 4500, 'barcode' => '', 'name_ar' => "سرکت تخدير ابو فلترين", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 240, 'unit_price' => 650, 'barcode' => '', 'name_ar' => "ميكرودروب ابو 150", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 241, 'unit_price' => 550, 'barcode' => '', 'name_ar' => "موصلات تقطير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 242, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "موصلات قرب دم", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 243, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "سكشن تيوب مقاس 10", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 244, 'unit_price' => 30, 'barcode' => '', 'name_ar' => "سيرنج 5 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 245, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "سيرنج 20 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 246, 'unit_price' => 30, 'barcode' => '', 'name_ar' => "سيرنج 3 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 247, 'unit_price' => 50, 'barcode' => '', 'name_ar' => "سيرنج ابو 10", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 248, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "سيرنج ابو 50 تغذية", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 249, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "سيرنج ابو 50 مل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 250, 'unit_price' => 200, 'barcode' => '01184275990614001728040010لإ07923', 'name_ar' => "خيوط سلك اسباني كتنج مقاس 2.0", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 251, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "كاثيولا 26", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 252, 'unit_price' => 250, 'barcode' => '', 'name_ar' => "كاثيولا مقاس 24 قصير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 253, 'unit_price' => 500, 'barcode' => '', 'name_ar' => "ثري وي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 254, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "جلفز لاتكس ماليزي مع البودر اسمول", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 255, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "الكترود ECG صغير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 256, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "الكترود ECG كبير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 257, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "کاندم بول L", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 258, 'unit_price' => 150, 'barcode' => '', 'name_ar' => "الصق عجل مقاس 2.5x1", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 259, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "الصق عجل مقاس 2.5x3", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 260, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "لصق عمليات 10x10 عبوة 25", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 261, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "لصق عمليات 15x10 عبوة 50", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 262, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "لصق عمليات 30x10 عبوة 50", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 263, 'unit_price' => 50, 'barcode' => '6925654645480', 'name_ar' => "جلفز فينال ابيض مقاس مديم M عبوة 100 حبة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 264, 'unit_price' => 600, 'barcode' => '6288009000410', 'name_ar' => "فاین مبلل صغير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 265, 'unit_price' => 800, 'barcode' => '6288009000434', 'name_ar' => "فاين مبلل كبير", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 266, 'unit_price' => 700, 'barcode' => '6288009000427', 'name_ar' => "فاین مبلل وسط", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 267, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "رباط ضاغط مقاس 3x10", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 268, 'unit_price' => 400, 'barcode' => '', 'name_ar' => "رباط ضاغط مقاس 15", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 269, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "رباط ضاغط مقاس 7.5", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 270, 'unit_price' => 50, 'barcode' => '', 'name_ar' => "كمام ربل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 271, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "اندر تركل تيوب مع الكف 2.5 njt", 'name_en' => "njt", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 272, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "اندر تركل تيوب مع الكف 3.5 njt", 'name_en' => "njt", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 273, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "اندر تركل تيوب مع الكف 4 njt", 'name_en' => "njt", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 274, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "اندر تركل تيوب مع الكف 6 njt", 'name_en' => "njt", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 275, 'unit_price' => 600, 'barcode' => '', 'name_ar' => "اندر تركل تيوب مع الكف 7 njt", 'name_en' => "njt", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 276, 'unit_price' => 250, 'barcode' => '8902120400581', 'name_ar' => "فيدنق تيوب 6", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 277, 'unit_price' => 250, 'barcode' => '8902120400598', 'name_ar' => "فيدنق تيوب 6", 'name_en' => "ngt", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 278, 'unit_price' => 200, 'barcode' => '', 'name_ar' => "سكشن تيوب مقاس 6", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 279, 'unit_price' => 50, 'barcode' => '', 'name_ar' => "سيرنج أبو 1 انسولين", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 280, 'unit_price' => 250, 'barcode' => '', 'name_ar' => "نازل اكسجين لارج", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 281, 'unit_price' => 100, 'barcode' => '', 'name_ar' => "علب براز معقم", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 282, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "ثري وي", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 283, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بوليميكورت ٥ ملح مل محلول ناتكو", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 284, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "بوتاسيوم امبول ابو فارع الغيالة", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 285, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "صوديوم بيكربونات فيال ٥٠مل ابو فارع", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 286, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "سومازينا امبول ۱۰۰۰ ملح الشرق . امبولات", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 287, 'unit_price' => 350, 'barcode' => '', 'name_ar' => "جلكونات كالسيوم ١٠ مل امبول رویال فارما", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 288, 'unit_price' => 0, 'barcode' => '', 'name_ar' => "اسیست امبول المفضل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 289, 'unit_price' => 2000, 'barcode' => '8436025480046', 'name_ar' => "سومازينا امبول 1جرام الشرق", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 290, 'unit_price' => 600, 'barcode' => '8699570750020', 'name_ar' => "اسيست امبول المفضل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 291, 'unit_price' => 800, 'barcode' => '', 'name_ar' => "دوبتامين امبول 5 هندي نامان", 'name_en' => "dobucard", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 292, 'unit_price' => 38000, 'barcode' => '6224000821760', 'name_ar' => "كلوجرستات فيال مصري ثرمبوستات", 'name_en' => "clograstat 12.5mg", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 293, 'unit_price' => 800, 'barcode' => '8904092902599', 'name_ar' => "نورادرنالين 4ملج امبولات", 'name_en' => "noradrinaline", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 294, 'unit_price' => 1200, 'barcode' => '7321839712241', 'name_ar' => "بوليميكورت 5ملج محلول ناتكو", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 295, 'unit_price' => 300, 'barcode' => '', 'name_ar' => "بوتاسيوم امبول ابو فارع الفيالة", 'name_en' => "kcl 15%", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 296, 'unit_price' => 1400, 'barcode' => '', 'name_ar' => "صوديم بيكربونات", 'name_en' => "sodium bicarbonate 50ml", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 298, 'unit_price' => 400, 'barcode' => '', 'name_ar' => "اكستنشن تيوب", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //         ['id' => 299, 'unit_price' => 1200, 'barcode' => '6253503197485', 'name_ar' => "فاين جاف فل", 'name_en' => "", 'scientific_name' => '', 'company_id' => ''],
        //     ]
        // );
    }


    public function v1(): void
    {
        Product::factory()->createMany([
            ['id' => 1, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي رقم واحد مواليد 66', 'name_en' => ''],
            ['id' => 2, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي رقم 483', 'name_en' => ''],
            ['id' => 3, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي رقم 2 66', 'name_en' => ''],
            ['id' => 4, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي عائلي عبوه 44 رقم 4', 'name_en' => ''],
            ['id' => 5, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي مواليد رقم 1 44', 'name_en' => ''],
            ['id' => 6, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي رقم 702', 'name_en' => ''],
            ['id' => 7, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي رقم 603', 'name_en' => ''],
            ['id' => 8, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي رقم 4 50', 'name_en' => ''],
            ['id' => 9, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'مناديل مبلله دادي عبوه 72', 'name_en' => ''],
            ['id' => 10, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'مناديل مبلله زين عبوه 120 حبه', 'name_en' => ''],
            ['id' => 11, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاين قل عايلي 1300 الاصفر', 'name_en' => ''],
            ['id' => 12, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب فرانس ليه رقم 1', 'name_en' => ''],
            ['id' => 13, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب فرانس ليه رقم 2', 'name_en' => ''],
            ['id' => 14, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب رجلاك رقم 1', 'name_en' => ''],
            ['id' => 15, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب رجلاك رقم 2', 'name_en' => ''],
            ['id' => 16, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب رجلاك رقم 3', 'name_en' => ''],
            ['id' => 17, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب فرانس ليه رقم 3', 'name_en' => ''],
            ['id' => 18, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رز مصری غذام', 'name_en' => ''],
            ['id' => 19, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بسكويت بسكي اطفال .', 'name_en' => ''],
            ['id' => 20, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرلاك غذاء مبكت منوع.', 'name_en' => ''],
            ['id' => 21, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اعواد اذان خشب 100', 'name_en' => ''],
            ['id' => 22, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اعواد اذن خشب صيني 200 حبه خليل كبير', 'name_en' => ''],
            ['id' => 23, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'معجون دابر بالأعشاب مع الفرشاة', 'name_en' => ''],
            ['id' => 24, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سجنال معجون وسط الاصلي', 'name_en' => ''],
            ['id' => 25, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'معجون سجنال صغير اصلي', 'name_en' => ''],
            ['id' => 26, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'معجون سجنال كبير سعودي 125 مل', 'name_en' => ''],
            ['id' => 27, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فرش استان سبتادینت', 'name_en' => ''],
            ['id' => 28, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فرش اسنان سيلكون الأصلي دكتور', 'name_en' => ''],
            ['id' => 29, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فرش اطفال اورنج ابو غطا', 'name_en' => ''],
            ['id' => 30, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون جونسون اطفال جديد', 'name_en' => ''],
            ['id' => 31, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون مينا بابايا', 'name_en' => ''],
            ['id' => 32, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون ديتول كبير اصلي', 'name_en' => ''],
            ['id' => 33, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون لوكس صغير', 'name_en' => ''],
            ['id' => 34, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون لايفبوي سعودي صغير', 'name_en' => ''],
            ['id' => 35, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون دوف صغير المالي', 'name_en' => ''],
            ['id' => 36, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رضاعات الامير كبير', 'name_en' => ''],
            ['id' => 37, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رضاعات مواليد الأمير 60 ملي', 'name_en' => ''],
            ['id' => 38, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رضاعات بتاتو وسط معتم 150 مل', 'name_en' => ''],
            ['id' => 39, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت الزيتون المروى', 'name_en' => ''],
            ['id' => 40, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت الزيتون ليدي بلاص 175 مل', 'name_en' => ''],
            ['id' => 41, 'unit_price' => 0, 'barcode' => '', 'name_ar' => '- زيت جونسون اطفال الاصلي 200 مل', 'name_en' => ''],
            ['id' => 42, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت اطفال بيدا 200 مل', 'name_en' => ''],
            ['id' => 43, 'unit_price' => 0, 'barcode' => '', 'name_ar' => '- زيت نونو 200 مل', 'name_en' => ''],
            ['id' => 44, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر 400 جرام مع شامبو 100 مل دعايه', 'name_en' => ''],
            ['id' => 45, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر صغير شامبو دعايه 50 مل', 'name_en' => ''],
            ['id' => 46, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر كبير 600 مع شامبو 100 مل دعايه', 'name_en' => ''],
            ['id' => 47, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر وسط 200 مع شامبو 50 مل دعايه', 'name_en' => ''],
            ['id' => 48, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شحم كوبرا 180 جرام وسط', 'name_en' => ''],
            ['id' => 49, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حفاضات لاكي بالغين كبير 30 حبة', 'name_en' => ''],
            ['id' => 50, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حفاضات لاكي بالغين وسط 30 حبة', 'name_en' => ''],
            ['id' => 51, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شحم كوبرا 180 جرام وسط', 'name_en' => ''],
            ['id' => 52, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شحم كوبر صغير جدا 45 جرام', 'name_en' => ''],
            ['id' => 53, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت فاتيكا منوع صغير', 'name_en' => ''],
            ['id' => 54, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت فاتيكا منوع كبير', 'name_en' => ''],
            ['id' => 55, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شامبو اطفال بيبي شوف 100 ملي', 'name_en' => ''],
            ['id' => 56, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شامبو اطفال بيبي شوف 200 ملي', 'name_en' => ''],
            ['id' => 57, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شامبو اطفال بيبي شوف 800 ملى -', 'name_en' => ''],
            ['id' => 58, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نيقياء ألماني كبير 250 جرام', 'name_en' => ''],
            ['id' => 59, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نيفياء ألماني وسط', 'name_en' => ''],
            ['id' => 60, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كريم جليسوليد كبير', 'name_en' => ''],
            ['id' => 61, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'گریم جليسوليد وسط', 'name_en' => ''],
            ['id' => 62, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كريم جليسوليد صغير مع الاضافة', 'name_en' => ''],
            ['id' => 63, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصقة عمليات 55 عبوة 50 سران', 'name_en' => ''],
            ['id' => 64, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات 2010 عبوه 25', 'name_en' => ''],
            ['id' => 65, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات تايجر 2510', 'name_en' => ''],
            ['id' => 66, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'غذاء ريرى بدون مرتجع', 'name_en' => ''],
            ['id' => 67, 'unit_price' => 1500, 'barcode' => '9501101272248', 'name_ar' => 'اوجمين شراب ۲۲۸ ملجم الدوانية الحديثة', 'name_en' => ''],
            ['id' => 68, 'unit_price' => 1100, 'barcode' => '9501101270138', 'name_ar' => 'موكسالين ٢٥٠ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 69, 'unit_price' => 1400, 'barcode' => '9501101270190', 'name_ar' => 'او جمين ١٥٦ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 70, 'unit_price' => 1800, 'barcode' => '9501101270206', 'name_ar' => 'اوجمين ۳۱۲ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 71, 'unit_price' => 1900, 'barcode' => '9501101270930', 'name_ar' => 'اوجمين ٤٥٧ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 72, 'unit_price' => 400, 'barcode' => '9501101270619', 'name_ar' => 'قومين ٧٥ اقراص الدوائية الحديثة', 'name_en' => ''],
            ['id' => 73, 'unit_price' => 5000, 'barcode' => '6291100082711', 'name_ar' => 'كبير ميبو مرهم ٣٠ جرام جلفار', 'name_en' => ''],
            ['id' => 74, 'unit_price' => 1000, 'barcode' => '6221094500786', 'name_ar' => 'جوافا شراب ۱۲۰ مل الرشيد سعال', 'name_en' => ''],
            ['id' => 75, 'unit_price' => 500, 'barcode' => '6221088021440', 'name_ar' => 'نيتروماك ريتارد ٢.٥ ملجم ٦٠ك الفتح', 'name_en' => ''],
            ['id' => 76, 'unit_price' => 800, 'barcode' => '6223000012062', 'name_ar' => 'فاركونسيل ١٢٥ ملجم شراب ٨٠ مل فاركو موكسالين', 'name_en' => ''],
            ['id' => 77, 'unit_price' => 900, 'barcode' => '6223000012079', 'name_ar' => 'فاركونسيل ٢٥٠ منجم شراب ٨٠ مل قار کو موكسالين', 'name_en' => ''],
            ['id' => 78, 'unit_price' => 150, 'barcode' => '6221151015307', 'name_ar' => 'فيتامين سي ۱۰۰۰ مل ظروف فاركو فوار سي', 'name_en' => ''],
            ['id' => 79, 'unit_price' => 100, 'barcode' => '6223000011515', 'name_ar' => 'يوريكول فرار ١٢ كيس فاركو', 'name_en' => ''],
            ['id' => 80, 'unit_price' => 600, 'barcode' => '', 'name_ar' => 'اسبرين مغلف ٧٥ ملجم اقراص المحضار اخوان', 'name_en' => 'aspirin 75mg'],
            ['id' => 81, 'unit_price' => 1000, 'barcode' => '540323725902', 'name_ar' => 'سيبرولون ٢٥ ملح أقراص الكتون أمير الدين', 'name_en' => ''],
            ['id' => 82, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => 'كلين انما حقن شرجية كبار العزاني', 'name_en' => 'kleen ename_enma 135ml'],
            ['id' => 83, 'unit_price' => 1400, 'barcode' => '6291109120100', 'name_ar' => 'بندول شراب للرضع بنكة الفراولة المنصوب', 'name_en' => ''],
            ['id' => 84, 'unit_price' => 2200, 'barcode' => '6291109120681', 'name_ar' => 'بندول شراب أزرق للأطفال اليكسير ١٠٠ مل المنصوب', 'name_en' => ''],
            ['id' => 85, 'unit_price' => 300, 'barcode' => '6091403219964', 'name_ar' => 'سولبادين فوار المنصوب', 'name_en' => ''],
            ['id' => 86, 'unit_price' => 900, 'barcode' => '6291109120339', 'name_ar' => 'بندول اكستر - المنصوب وكالة', 'name_en' => ''],
            ['id' => 87, 'unit_price' => 1250, 'barcode' => '5997001359426', 'name_ar' => 'نورمادبين 5 ملجم اقراص بلقيس', 'name_en' => 'normodipiname_en 5mg'],
            ['id' => 88, 'unit_price' => 1650, 'barcode' => '5997001359433', 'name_ar' => 'نورمادبين ١٠ ملم اقراص بلقيس', 'name_en' => ''],
            ['id' => 89, 'unit_price' => 950, 'barcode' => '8901117265158', 'name_ar' => 'اتروليب ١٠ ملجم اقراص ٣٠ ٤ سيبلا', 'name_en' => ''],
            ['id' => 90, 'unit_price' => 1350, 'barcode' => '8901117266049', 'name_ar' => 'اتروليب ۲۰ ملجم اقراص ٣٠ سيبلا', 'name_en' => ''],
            ['id' => 91, 'unit_price' => 2300, 'barcode' => '8901117266018', 'name_ar' => 'اتروليب ٤٠ ملجم اقراص ۱۰ ق سيبلا', 'name_en' => ''],
            ['id' => 92, 'unit_price' => 1100, 'barcode' => '8901117266445', 'name_ar' => 'ديتور ١٠ ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 93, 'unit_price' => 1500, 'barcode' => '8901117265974', 'name_ar' => 'ديتور ۲۰ ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 94, 'unit_price' => 1000, 'barcode' => '8901117268616', 'name_ar' => 'بانتوسيك ٤٠ ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 95, 'unit_price' => 4500, 'barcode' => '8002660033543', 'name_ar' => 'دوفلاك شراب الراقة بدون مرتجع', 'name_en' => ''],
            ['id' => 96, 'unit_price' => 800, 'barcode' => '4031571068980', 'name_ar' => 'نيادي بنك ريتارد ۲۰ ملجم ۱۰۰ الغزالي', 'name_en' => ''],
            ['id' => 97, 'unit_price' => 800, 'barcode' => '9504000288747', 'name_ar' => 'ايبوفلام شراب ۱۰۰ مل كبير شفاكو', 'name_en' => ''],
            ['id' => 98, 'unit_price' => 300, 'barcode' => '9504000269173', 'name_ar' => 'اسبيكوت ٧٥ ملجم اقراص شفاكو أسبرين مختلف', 'name_en' => ''],
            ['id' => 99, 'unit_price' => 1700, 'barcode' => '9504000269340', 'name_ar' => 'كلوفال ٧٥ ملح اقراص ۲۸ قرص شفاكو بلافيكس كلوبي', 'name_en' => ''],
            ['id' => 100, 'unit_price' => 1200, 'barcode' => '9504000288334', 'name_ar' => 'اكسوبان ٤٠ ملجم كبسول ٣٠ ك بانتوبرازول شفاكو', 'name_en' => ''],
            ['id' => 101, 'unit_price' => 50, 'barcode' => '9504000269203', 'name_ar' => 'فولتين دي تي شفاكو ايمفيناك', 'name_en' => ''],
            ['id' => 102, 'unit_price' => 250, 'barcode' => '9504000269692', 'name_ar' => 'امول اقراص صغير شفاكر', 'name_en' => ''],
            ['id' => 103, 'unit_price' => 50, 'barcode' => '9504000269814', 'name_ar' => 'امول اكسترا شريطين اقراص شفاكو', 'name_en' => ''],
            ['id' => 104, 'unit_price' => 100, 'barcode' => '9504000288198', 'name_ar' => 'ميوفيت سي أكياس ۱۰۰۰ ملجم شفاكو فيتامين سي', 'name_en' => ''],
            ['id' => 105, 'unit_price' => 50, 'barcode' => '9504000269265', 'name_ar' => 'او ميتوب ۲۰ ملجم اقراص شفاكو', 'name_en' => ''],
            ['id' => 106, 'unit_price' => 1000, 'barcode' => '6211057011039', 'name_ar' => 'فيتامين سي صافي فوار القادري فيت سي', 'name_en' => ''],
            ['id' => 107, 'unit_price' => 1000, 'barcode' => '6211057021038', 'name_ar' => 'كالسيوم فيتامين سي فوار القادري كالسيفيت', 'name_en' => ''],
            ['id' => 108, 'unit_price' => 200, 'barcode' => '', 'name_ar' => 'سولباقيز فوار رويال سولبادين', 'name_en' => 'solpafizz 65mg'],
            ['id' => 109, 'unit_price' => 750, 'barcode' => '6224000486693', 'name_ar' => 'کولداکت شراب بیوفارم فلوكيت فلودرين', 'name_en' => ''],
            ['id' => 110, 'unit_price' => 50, 'barcode' => '6224000486075', 'name_ar' => 'كولداكت كبسول بيوفارما فلوتاب', 'name_en' => ''],
            ['id' => 111, 'unit_price' => 100, 'barcode' => '6291103730459', 'name_ar' => 'امفيناك دي تي ٥٠ ملجم ك النهدي ديكلوفين', 'name_en' => ''],
            ['id' => 112, 'unit_price' => 450, 'barcode' => '8901040310024', 'name_ar' => 'زبین شراب رنتل الجبر فارما', 'name_en' => ''],
            ['id' => 113, 'unit_price' => 300, 'barcode' => '8901040310031', 'name_ar' => 'زبين ۲۰۰ ملجم زنتل / اقراص الجبر فارما', 'name_en' => ''],
            ['id' => 114, 'unit_price' => 700, 'barcode' => '6221043012971', 'name_ar' => 'ماء سيد شراب الوراقي ماء غريب', 'name_en' => ''],
            ['id' => 115, 'unit_price' => 1500, 'barcode' => '6221025025234', 'name_ar' => 'ابیدون ١٢٥ ملجم شراب أمون القاهرة', 'name_en' => ''],
            ['id' => 116, 'unit_price' => 700, 'barcode' => 'ٍأ-012-01-253', 'name_ar' => 'بيروفين قطر سباء فارما', 'name_en' => ''],
            ['id' => 117, 'unit_price' => 750, 'barcode' => '745604596718', 'name_ar' => 'هستات شراب ١٠٠ مل سباء فارما', 'name_en' => ''],
            ['id' => 118, 'unit_price' => 750, 'barcode' => '745604597227', 'name_ar' => 'موتلين ٦٠ ملجم شراب سباء فارما', 'name_en' => ''],
            ['id' => 119, 'unit_price' => 700, 'barcode' => 'ٍأ-012-03-072', 'name_ar' => 'هكساديل مضمضه ١٠٠ مل سباء فارما', 'name_en' => ''],
            ['id' => 120, 'unit_price' => 1850, 'barcode' => '745604598699', 'name_ar' => 'فالسيترى ٢٦/٢٤ ملجم ٣٠ قرص ساكو بلاص سفرماد', 'name_en' => ''],

            ['id' => 121, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => 'بانتوفكيس بانتوبرازول ٤٠ فيال اميال فارما ', 'name_en' => 'pantofix'],

            ['id' => 122, 'unit_price' => 250, 'barcode' => '745604596725', 'name_ar' => 'هستات اقرص ۲۰ ق سباء فارما', 'name_en' => ''],
            ['id' => 123, 'unit_price' => 700, 'barcode' => '745604597241', 'name_ar' => 'موتلين ٣٠ مل قطر سباء فارما', 'name_en' => ''],
            ['id' => 124, 'unit_price' => 400, 'barcode' => '8904092907648', 'name_ar' => 'يوتابين قيال ١.٢ فيال لاااااااب بعوم', 'name_en' => ''],
            ['id' => 125, 'unit_price' => 1750, 'barcode' => '8941100359600', 'name_ar' => 'جارديان ۱۰ ملج القرص ايمبافت ابن القادري', 'name_en' => ''],
            ['id' => 126, 'unit_price' => 1650, 'barcode' => '8941100359617', 'name_ar' => 'جارديان ٢٥ ملجم اقرص ايمپافنت ابن القادري -', 'name_en' => ''],
            ['id' => 127, 'unit_price' => 1400, 'barcode' => '9501101277120', 'name_ar' => 'ايمبا ١٠ ملجم اقراص العالميه ايمباقنت', 'name_en' => ''],
            ['id' => 128, 'unit_price' => 2100, 'barcode' => '9501101277168', 'name_ar' => 'ايمبا ٢٥ ملجم اقراص العالميه ايمبافنت', 'name_en' => ''],
            ['id' => 129, 'unit_price' => 800, 'barcode' => 'إُ-01-029-11', 'name_ar' => 'أمبروفين فراولة ۱۰۰مل اليمنية المصرية 7', 'name_en' => ''],
            ['id' => 130, 'unit_price' => 1900, 'barcode' => '6251106160158', 'name_ar' => 'لينوبريل ١٠ ملجم اقراص الدولية الاردنية', 'name_en' => ''],
            ['id' => 131, 'unit_price' => 1250, 'barcode' => '6251106160103', 'name_ar' => 'لينوبريل 5ملجم اقراص الدولية الأردنية', 'name_en' => ''],
            ['id' => 132, 'unit_price' => 400, 'barcode' => '8901117266414', 'name_ar' => 'اسبين 100 ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 133, 'unit_price' => 50, 'barcode' => '8901117264298', 'name_ar' => 'لوماك ۲۰ منجم كبسول أشرطة سيبلا', 'name_en' => ''],
            ['id' => 134, 'unit_price' => 3200, 'barcode' => '', 'name_ar' => 'ميبو مرهم صغير أبو زيد', 'name_en' => ''],
            ['id' => 135, 'unit_price' => 400, 'barcode' => '6212035090381', 'name_ar' => 'فاديرين 81 ملجم اقراص هيلثي فارما جوسبرين -', 'name_en' => ''],
            ['id' => 136, 'unit_price' => 1300, 'barcode' => '8905887002258', 'name_ar' => 'ابيكسان هيل 5 ملجم اقراص ابيكسا هيلان', 'name_en' => ''],
            ['id' => 137, 'unit_price' => 50, 'barcode' => '8904159404622', 'name_ar' => 'سكو فاست اقراص العابد امفيناك بدون مرتجع', 'name_en' => ''],
            ['id' => 138, 'unit_price' => 800, 'barcode' => '6210236134187', 'name_ar' => 'بوفين شراب ۱۰۰مل الخياط امبروفين شراب', 'name_en' => ''],

            ['id' => 139, 'unit_price' => 4500, 'barcode' => '3664798036558', 'name_ar' => 'بلافيكس ٧٥ ملجم اقراص الصباري -بانتوبرازول ٤٠ فيال اميال فارما بالتوفيكس', 'name_en' => ''],

            ['id' => 140, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موكسالين ١٢٥ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 141, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'توسكان شراب الجبل', 'name_en' => ''],
            ['id' => 142, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيستول ۲٫٥ ملغ اقراص الجبل', 'name_en' => ''],
            ['id' => 143, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بیستول ٥ ملغ اقراص عادي الجبل', 'name_en' => ''],
            ['id' => 144, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سوفيكان ٢٠ ملغ اقراص الجبل', 'name_en' => ''],
            ['id' => 145, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سوفيكان ١٠ ملح أقراص الجبل الحكمه', 'name_en' => ''],
            ['id' => 146, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موتيل ١٠٠مل موتلين شراب العالمية', 'name_en' => ''],
            ['id' => 147, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نيولاكس ۱۰۰ مل شراب العالمية لاكسولاك', 'name_en' => ''],
            ['id' => 148, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'هايبين ٥٠٠مل اقراص الجبل أموكسيل ۱۰ ش', 'name_en' => ''],
            ['id' => 149, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بیمناست ۱۰۰۰ ملجم فيال العربية فوربار', 'name_en' => ''],
            ['id' => 150, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زوراكسون ۱۰۰۰ ملجم وريدي الفتح فورسيف', 'name_en' => ''],
            ['id' => 151, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيفوران 1 جرام فيال فارکو اور تاکسیم', 'name_en' => ''],
            ['id' => 152, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'باراسيتامول قرب برفلجان فاركو', 'name_en' => ''],
            ['id' => 153, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اور تکسیم اجرام فيال الجبل', 'name_en' => ''],
            ['id' => 154, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيفتاد ۱۰۰۰ قيال فوربار الجبل', 'name_en' => ''],
            ['id' => 155, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قوربار اجرام فيال سيبلا', 'name_en' => ''],
            ['id' => 156, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'انسولين اتش بيو ار فيال أصفر) سيديكو الحارث', 'name_en' => ''],
            ['id' => 157, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'هيبارين صوديوم ٥٠٠٠ وحدة عبوة 3 أمبولات جديد الحارث', 'name_en' => ''],
            ['id' => 158, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبروفلوكساسين محلول العافية سيبلوكس', 'name_en' => ''],
            ['id' => 159, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ديكساميتازون امبول فلهوم', 'name_en' => ''],
            ['id' => 160, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زجاج برفلجان قرب زجاج فلهوم', 'name_en' => ''],
            ['id' => 161, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ديكستروز ٤٠% امبول رويال فارما بالحبه الواحده', 'name_en' => ''],
            ['id' => 162, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'براسيتامول مغنيات زجاج رويال بر فلجان رویامول', 'name_en' => ''],
            ['id' => 163, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اقيل امبول رويال فارما', 'name_en' => ''],
            ['id' => 164, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بليمازول امبول رويال فارما ريمو بلازا', 'name_en' => ''],
            ['id' => 165, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بي كومبلكس أمبول رويال فارما', 'name_en' => ''],
            ['id' => 166, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيتامين سي أمبول ٥٠٠ رويال فارما', 'name_en' => ''],
            ['id' => 167, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جنتاميسين أمبول ۸۰ ملجم رويال فارما', 'name_en' => ''],
            ['id' => 168, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'متريندازول قرب جال فارما فلاجيل بدون موصل', 'name_en' => ''],
            ['id' => 169, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'انترابيم قيال مياس 1 جرام سيفبيم قوربار', 'name_en' => ''],
            ['id' => 170, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'باراكونيكا اجرام فيال محلات مياس برفلجان', 'name_en' => ''],
            ['id' => 171, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمبونينت فيال ۲۰ ف أرض الجنتين كومبيفيت', 'name_en' => ''],
            ['id' => 172, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'دوبروس ۲۰۰ مل امبول دوبامين بعوم', 'name_en' => ''],
            ['id' => 173, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'وکیل مختوم تینام ٥٠٠ ملجم بان مبنيم مهدي الشاعر', 'name_en' => ''],
            ['id' => 174, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فانكومايسين اجرام فيال الشاعر فانكولون ۱۰۰۰', 'name_en' => ''],
            ['id' => 175, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ستو بالجيك برفلجان بارستامول مغنية الشاعر', 'name_en' => ''],
            ['id' => 176, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبروفلوكساسين قرب الجيش سيبلوكس سيبروكيد', 'name_en' => ''],
            ['id' => 177, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبلاسيف اجرام فيال سيبلا', 'name_en' => ''],
            ['id' => 178, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبلاسيف ٥٠٠ ملجم فيال سيبلا', 'name_en' => ''],
            ['id' => 179, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سیلاكيب ٥٠٠ جرام فيال تينام رسام الشاعر', 'name_en' => ''],
            ['id' => 180, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موبيم ا مجم فيال رسام الشاعر میرونیم مورنیم بدون مرتجع', 'name_en' => ''],
            ['id' => 181, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'دايميد ۲۰ منجم امبول الربيعي ديتور ١٠ امبول', 'name_en' => ''],
            ['id' => 182, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سكر مغنيات الجبل', 'name_en' => ''],
            ['id' => 183, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رنجر مغذيات الجبل', 'name_en' => ''],
            ['id' => 184, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فلاجيل قرب مع الموصلات اميال فارما بدون مرتجع', 'name_en' => ''],
            ['id' => 185, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' روها ليفوفلوكساسين قرب ۱۰۰ مل روها فارما معى الموصل ليلوباكت', 'name_en' => ''],
            ['id' => 186, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' روها سيبروفلوكساسين قرب ۱۰۰ مل روها فارما معى الموصل سيبلوكس', 'name_en' => ''],
            ['id' => 187, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' اوندر يسترون امبول ۸ ملجم صادق البرحي ايمست', 'name_en' => ''],
            ['id' => 188, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' سالاتاز ٤٥ فيال الأمل تاركت', 'name_en' => ''],
            ['id' => 189, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' لازكس امبول الصباري', 'name_en' => ''],
            ['id' => 190, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' هيتاسون ۱۰۰ ملجم فيال فارما بيدا هيدروكرتزون', 'name_en' => ''],
            ['id' => 191, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' بروسيوم ١٠ امبول امبولات فارما بيدا مغناسيوم', 'name_en' => ''],
            ['id' => 192, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' سيفتر یاکسون أكوي اجم فيال تعافي فارما سي ون سيبلاسيف', 'name_en' => ''],
            ['id' => 193, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' نازکت کوزمابيتاز ٤,٥ ملجم قرب الجيش تازكت', 'name_en' => ''],
            ['id' => 194, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' كورما تكسي اجرام فيال اور تكسيم سيفوتاكسيم الجيش و', 'name_en' => ''],
            ['id' => 195, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ديتور امبول عبوة ۲۰ امبوله ابوزيد سيبلا ٢٠ أم', 'name_en' => ''],
            ['id' => 196, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ميراكوي اجم فيال تعافي فارما ميرونيم', 'name_en' => ''],
            ['id' => 197, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' افسيناف اجم فيال فانكومايسين تعافي فارما', 'name_en' => ''],
            ['id' => 198, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' اینوکس بارين ٤٠٠٠ و دتعافي فارما ٢ أمبول', 'name_en' => ''],
            ['id' => 199, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' اینو كسبارين ٦٠٠٠ و دتعافي فارما ٢ امبول', 'name_en' => ''],
            ['id' => 200, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' کابرین ۲۵۰۰۰ و.د فيال فارما بيوتك هيبارين', 'name_en' => ''],
            ['id' => 201, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ملح مغنيات القطريفي', 'name_en' => ''],
            ['id' => 202, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' مخلوط مغذيات القطريفي', 'name_en' => ''],
            ['id' => 203, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فانكوبال ۱۰۰۰ ملجم فيال أميال فانكوميسين', 'name_en' => ''],
            ['id' => 204, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' سوكسيبال مغذيات اميال فارما موكساسيب', 'name_en' => ''],
            ['id' => 205, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فير سدرين ٢ ملي أمبول لازكس بريميم ديرين', 'name_en' => ''],
            ['id' => 206, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' درسترون ۲ ملي أمبول ايمست بریمیم دیرین', 'name_en' => ''],
            ['id' => 207, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ليفيتام ٥٠٠ ملجم فيال كيبرا بیوسنسورس بيواكتف', 'name_en' => ''],
            ['id' => 208, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فاتكولون ۱۰۰۰ ملجم فيال جلفار', 'name_en' => ''],
            ['id' => 209, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' روها میترندازول ۱۰۰ ما قرب روها فارما معى الموصل فلاجيل', 'name_en' => ''],
            ['id' => 210, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 16', 'name_en' => ''],
            ['id' => 211, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 14', 'name_en' => ''],
            ['id' => 212, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 12', 'name_en' => ''],
            ['id' => 213, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون ابو 10', 'name_en' => ''],
            ['id' => 214, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 6', 'name_en' => ''],
            ['id' => 215, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 8', 'name_en' => ''],
            ['id' => 216, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قرب بول', 'name_en' => ''],
            ['id' => 217, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شاش معقم 10*10 عبوة 50', 'name_en' => ''],
            ['id' => 218, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلفز معقم ماليزي 7.5', 'name_en' => ''],
            ['id' => 219, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رایز تیوب مقاس 16', 'name_en' => ''],
            ['id' => 220, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رايز تيوب مقاس 14', 'name_en' => ''],
            ['id' => 221, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رایز تیوب مقاس 12', 'name_en' => ''],
            ['id' => 222, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سنتر لاين مقاس 7', 'name_en' => ''],
            ['id' => 223, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سنتر لاين مقاس 3', 'name_en' => ''],
            ['id' => 224, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 50 جرام', 'name_en' => ''],
            ['id' => 225, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رايز تيوب مقاس 8', 'name_en' => ''],
            ['id' => 226, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيدنق تيوب 10', 'name_en' => ''],
            ['id' => 227, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 100 جرام', 'name_en' => ''],
            ['id' => 228, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن 500 جرام', 'name_en' => ''],
            ['id' => 229, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 1000 جرام', 'name_en' => ''],
            ['id' => 230, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 250', 'name_en' => ''],
            ['id' => 231, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام اكسجين اسمول', 'name_en' => ''],
            ['id' => 232, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام اكسجين مديم', 'name_en' => ''],
            ['id' => 233, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام اكسجين كبار', 'name_en' => ''],
            ['id' => 234, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام نيو بليزر اسمول', 'name_en' => ''],
            ['id' => 235, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام نيو بليزر لارج', 'name_en' => ''],
            ['id' => 236, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر باد صيني عبوة 25', 'name_en' => ''],
            ['id' => 237, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سركت تخدير اطفال', 'name_en' => ''],
            ['id' => 238, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سركت تخدير كبار', 'name_en' => ''],
            ['id' => 239, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شرکت تخدير ابو فلترين', 'name_en' => ''],
            ['id' => 240, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'مكرو دروب ابو 150', 'name_en' => ''],
            ['id' => 241, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موصلات تقطير', 'name_en' => ''],
            ['id' => 242, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موصلات قرب دم', 'name_en' => ''],
            ['id' => 243, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سكشن تيوب مقاس 10', 'name_en' => ''],
            ['id' => 244, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج 5 مل', 'name_en' => ''],
            ['id' => 245, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج 20 مل', 'name_en' => ''],
            ['id' => 246, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج 3 مل', 'name_en' => ''],
            ['id' => 247, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج ابو 10', 'name_en' => ''],
            ['id' => 248, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج ابو 50 تغذية', 'name_en' => ''],
            ['id' => 249, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج ابو 50 مل', 'name_en' => ''],
            ['id' => 250, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'خيوط سلك اسباني كتنج مقاس 2.0', 'name_en' => ''],
            ['id' => 251, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كاثيولا 26', 'name_en' => ''],
            ['id' => 252, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كاثيولا مقاس 24 قصير', 'name_en' => ''],
            ['id' => 253, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ثري وي', 'name_en' => ''],
            ['id' => 254, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلفز لاتكس ماليزي مع البودر اسمول', 'name_en' => ''],
            ['id' => 255, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الكترود ECG', 'name_en' => ''],
            ['id' => 256, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الكترود ECG', 'name_en' => ''],
            ['id' => 257, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'کاندم بول L', 'name_en' => ''],
            ['id' => 258, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الصق عجل مقاس 2.51', 'name_en' => ''],
            ['id' => 259, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الصق عجل مقاس 2.53', 'name_en' => ''],
            ['id' => 260, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات 1010 عبوة 25', 'name_en' => ''],
            ['id' => 261, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات 1510 عبوة 50', 'name_en' => ''],
            ['id' => 262, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الصق عمليات 3010 عبوة 50', 'name_en' => ''],
            ['id' => 263, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلفز فينال ابيض مقاس مديم M', 'name_en' => ''],
            ['id' => 264, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاین مبلل', 'name_en' => ''],
            ['id' => 265, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاين مبلل كبير', 'name_en' => ''],
            ['id' => 266, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاین مبلل وسط', 'name_en' => ''],
            ['id' => 267, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رباط ضاغط مقاس 310', 'name_en' => ''],
            ['id' => 268, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رباط ضاغط مقاس 15', 'name_en' => ''],
            ['id' => 269, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رباط ضاغط مقاس 7.5', 'name_en' => ''],
            ['id' => 270, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام ربل', 'name_en' => ''],
            ['id' => 271, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 2.5', 'name_en' => ''],
            ['id' => 272, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 3.5', 'name_en' => ''],
            ['id' => 273, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 4', 'name_en' => ''],
            ['id' => 274, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 6', 'name_en' => ''],
            ['id' => 275, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 7', 'name_en' => ''],
            ['id' => 276, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيدنق تيوب 6', 'name_en' => ''],
            ['id' => 277, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيدنق تيوب 6', 'name_en' => ''],
            ['id' => 278, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سكشن تيوب مقاس 6', 'name_en' => ''],
            ['id' => 279, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج أبو 1 انسولين', 'name_en' => ''],
            ['id' => 280, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نازل اكسجين لارج', 'name_en' => ''],
            ['id' => 281, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'علب براز معقم', 'name_en' => ''],
            ['id' => 282, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ثري وي', 'name_en' => ''],
            ['id' => 283, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بوليميكورت ٥ ملح مل محلول ناتكو', 'name_en' => ''],
            ['id' => 284, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بوتاسيوم امبول ابو فارع الغيالة', 'name_en' => ''],
            ['id' => 285, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صوديوم بيكربونات فيال ٥٠مل ابو فارع', 'name_en' => ''],
            ['id' => 286, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سومازينا امبول ۱۰۰۰ ملح الشرق . امبولات', 'name_en' => ''],
            ['id' => 287, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلكونات كالسيوم ١٠ مل امبول رویال فارما', 'name_en' => ''],
            ['id' => 288, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اسیست امبول المفضل', 'name_en' => ''],

        ]);
    }
}
